### ISSUE TITLE
Can not Mint my DFI

### ISSUE THREAD

**Issue by 7Hatrick** [muirglacier/bridgev2#12]
After sending DFI from my Lightwallet to the my Metamask Bridge Adress i am not able to mint them on my BSC address.

i can find the Transaction on the "Bridgeaddress" and it shows, that its there (IN; like all the old transactions) but there is no OUT. 

It's not possible to mint. 
after pressing the mint token this error is shown:
SyntaxError: "undefined" is not valid JSON

i also tried the old Version of the bridge. also doesn't work.
 
looking forward to your help!

<img width="586" alt="Bildschirmfoto 2023-07-30 um 20 16 41" src="https://github.com/muirglacier/bridgev2/assets/140309772/14bae7d4-0d67-45b7-b2b3-91d8497c9460">

<img width="561" alt="Bildschirmfoto 2023-07-30 um 20 17 34" src="https://github.com/muirglacier/bridgev2/assets/140309772/8e254f2a-c53f-4e4d-944f-55d5640a3f72">

**Comment by 7Hatrick** [comment]
my TxID:
https://defiscan.live/transactions/5bc37bb5f3e78d3c44b15f1501de818385eb06d4544febddca5c8c12bcadb07f

**Comment by 7Hatrick** [comment]
Thanks Andy L.
He took care of it.
finally it worked

**Comment by clickback483** [comment]
Hi, how do you solved? Thank you

**Comment by Stonygan** [comment]
Please close Issue when problem is solved.

**Comment by 7Hatrick** [comment]
> After sending DFI from my Lightwallet to the my Metamask Bridge Adress i am not able to mint them on my BSC address.
> 
> i can find the Transaction on the "Bridgeaddress" and it shows, that its there (IN; like all the old transactions) but there is no OUT.
> 
> It's not possible to mint. after pressing the mint token this error is shown: SyntaxError: "undefined" is not valid JSON
> 
> i also tried the old Version of the bridge. also doesn't work.
> 
> looking forward to your help!
> 
> <img alt="Bildschirmfoto 2023-07-30 um 20 16 41" width="586" src="https://user-images.githubusercontent.com/140309772/257068620-14bae7d4-0d67-45b7-b2b3-91d8497c9460.png"> <img alt="Bildschirmfoto 2023-07-30 um 20 17 34" width="561" src="https://user-images.githubusercontent.com/140309772/257068714-8e254f2a-c53f-4e4d-944f-55d5640a3f72.png">

**Comment by 7Hatrick** [comment]
finally goes threw, like told on aug 2nd. thanks to all
