### ISSUE TITLE
Missing DFI on BSC, transaction on Ethereum

### ISSUE THREAD

**Issue by ghost** [muirglacier/bridgev2#13]
Hi guys,

I initiated a cross-chain swap DFICHain > Binance Chain, but didn't receive any DFI on BSC. The defichain bridge correcly detected the transaction on DFIChain, and the swap went through. After that, I was asked to mint the DFI on BSC, I signed the transaction, but nothing happened after that on BSC. The curious thing is that a transaction on the Ethereum chain happened at the same time on the same address as the one on BSC(0 ETH transacted). Is it possible that the minting transaction could have been initiated by the frontend on Ethereum instead of BSC ?

The DFIChain transaction : https://defiscan.live/transactions/98388f4a82d5b5ad270524533d11b06850527e8408a68e0b07c1975e85c02a66

The Ethereum transaction : 
https://etherscan.io/tx/0x678c4cf7f43663c5353fbdba2ffbe7ac36db1b9328f4d0680ff67454f6746ad7

Thanks for your time.

**Comment by nmtnjhxn** [comment]
5 days since my request, no answer.

**Comment by Stonygan** [comment]
Are you sure that you use the correct network in MetaMask? You must use Binance Smart chain.
You can use this article for more details. https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain
