### ISSUE TITLE
Can not Mint my DFI

### ISSUE THREAD

**Issue by clickback483** [muirglacier/bridgev2#14]
After sending DFI from my Jellywallet to the my Metamask Bridge Adress i am not able to mint them on my BSC address.

It's not possible to mint.
after pressing the mint token this error is shown:
SyntaxError: "undefined" is not valid JSON

![image](https://github.com/muirglacier/bridgev2/assets/143296350/054c0d33-5cc7-4c98-8118-5c8e07bbaae1)

looking forward to your help!
Thank you

**Comment by Stonygan** [comment]
Hello, please use the recovery funtion to mint the DFI again. You can find it at the end of the process, calles "Rescue Function"
