### ISSUE TITLE
No DFI (BSC) received 

### ISSUE THREAD

**Issue by michaelkoliver** [muirglacier/bridgev2#16]
I used the bridge to exchange DFI (DeFiChain) to DFI (BNB Smart Chain). I never received the latter. Here's the transaction:

https://defiscan.live/transactions/d9b99dbe965ea9502c62718a017c602f063d43d7ffde3edb7a7bc22f8823d9fe

**Comment by michaelkoliver** [comment]
?

**Comment by michaelkoliver** [comment]
Hello?

**Comment by Stonygan** [comment]
please try again the recover now.

![image](https://github.com/muirglacier/bridgev2/assets/44975826/41b81256-567f-4ca7-b962-a1b4c9114ce7)
