### ISSUE TITLE
Transaction Hash:0x5e2ad67a1ca0ecc270b599d1248a1adfa758a3e0d6d339ff62889bf95ccebc9e

### ISSUE THREAD

**Issue by warfloh** [muirglacier/bridgev2#19]
I did 2 transactions, first about 500 DFI from BSC to DFI wHich arrived at DFI wallet, after that I did againa transaction with 2000 DFI, this amount I not received at my DFI wallet.
At BSC - Metamask wallet the 2000 DFI are gone but not received at DFI wallet.
I try recovery-mode at bridge but was not working.

**Comment by DiabloBestHusky** [comment]
Hello, you copied this from my issue ? When you did this transactions ?

**Comment by warfloh** [comment]
sorry i did the transactions and same problem. My English is so bad that I copied your text.

**Comment by warfloh** [comment]
I really hope that I get help here and my DFI are not lost?!

**Comment by warfloh** [comment]
Is there nobody here who can help me?

**Comment by Stonygan** [comment]
Please try the recovery function:

![image](https://github.com/muirglacier/bridgev2/assets/44975826/6f2abc88-7b32-418b-9120-df30ba1b8ff0)

**Comment by warfloh** [comment]
Hello, unfortunately I suddenly had to go to a hospital and could not take care of it. I hope it's not too late to get the money back. It's a lot for me. I couldn't find the rescue function. Where can I find and use them to get my DFI back. I am very grateful for any help.

**Comment by warfloh** [comment]
Hello, unfortunately I suddenly had to go to a hospital and could not take care of it. I hope it's not too late to get the money back. It's a lot for me. I couldn't find the rescue function. Where can I find and use them to get my DFI back. I am very grateful for any help.

**Comment by warfloh** [comment]
Unfortunately, I can't find the rescue function. Can anyone please help me?. It's the first time I've used the brigde. After all, there are over 2000 DFIs that were lost.

**Comment by warfloh** [comment]
Because I didn't know what to do, I turned to the Defichain German group on Telegram with a request for help. There, an "admin" wrote to me and got me to agree to a transaction in order to get my lost DFI back. The result was that all my coins that were on Metamask were stolen. Thanks, thanks for the help.

**Comment by Stonygan** [comment]
https://github.com/muirglacier/bridgev2/issues/20
