### ISSUE TITLE
Can you fix my Swap - DFI -> BSC has not work

### ISSUE THREAD

**Issue by Otti24xx** [muirglacier/bridgev2#7]
My DFI TX: 32fcdd9e7fef9f5310614069e16b70f2518e011f092d89f84b017ff97149b67f

https://defiscan.live/transactions/32fcdd9e7fef9f5310614069e16b70f2518e011f092d89f84b017ff97149b67f

I have send 1443 DFI - and it has not work to bridge to BSC

**Comment by Otti24xx** [comment]
Message:

SyntaxError: "undefined" is not valid JSON

**Comment by Otti24xx** [comment]
Message on recovery on V1:

signatures have invalid length/count: 0

**Comment by 7Hatrick** [comment]
i have the same issue now.
what has helped you?

**Comment by Stonygan** [comment]
Please close Issue when problem is solved.
